---
- name: Intro to looping
  hosts: localhost        # target 127.0.0.1 (there's no place like home...)
  connection: local       # we do NOT want to SSH to ourselves (localhost)
  gather_facts: no        # no reason to define ansible_facts

  # "play_vars"
  vars:                   # vars available to all tasks
    ethList:
      - "eth0"
      - "eth1"
      - "eth2"
      - "eth3"

  tasks:
    - name: Demo a tiny loop
      debug:
        # item is always the var mapped to loop
        msg: "The debug module allows us to display to the screen: {{ item }}"
      loop: "{{ ethList }}"
      #loop_control:
          #index_var: sahilsVar

    - name: Demo a second tiny loop
      debug:
        # item is always the var mapped to loop
        msg: "All modules can also have LOCAL var information: {{ item }}"
      loop: "{{ myOtherList }}"
      vars:     # "task_vars"
        myOtherList:
          - "192.168.70.1"
          - "10.10.1.1"

